name: Android Build

on: [ push, pull_request ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone brave-browser repo
        uses: actions/checkout@v4
        with:
          repository: brave/brave-browser
          ref: v1.84.134

